version: '3.9'
services:
  bot:
    restart: always
    image: 'clxxiii/yagami-bot:latest'
    volumes:
      - './src/lib/prisma/db:/app/src/lib/prisma/db:rw'
    env_file:
      - .env
    ports:
      - '5555:5555'
  web:
    restart: always
    image: 'clxxiii/yagami-web:latest'
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - './src/lib/prisma/db:/app/src/lib/prisma/db:rw'
